ShadowBlip/InputPlumber

- src/input/event/dbus.rs
- src/input/target/dbus.rs
This change also includes additional events to translate like `ui_select`, `ui_[r|l][1,2,3]`, and `ui_action`.
> feat(DBusDevice): add support for analog input translation for dbus target

- src/input/event/dbus.rs
This change adds support for volume events over DBus.
> fix(DBus): add volume events for DBus

- src/input/composite_device/mod.rs
- Enables handling single events the same as how we handle on-release buttons. 
- Multi-button chords not yet supported.
> fix(CompositeDevice): Ensure direct_write events are properly delayed.

- src/input/composite_device/mod.rs
- Adds SendButtonChord DBus interface. This interface takes an array of button events and creates a Vec of InputEvents, first in the given order with pressed = true, then in reverse order with pressed = false.
- Renames DirectWrite to SendEvent for naming consistency.
> feat(CompositeDevice): Add SendButtonChord to dbus interface.

- src/input/composite_device/mod.rs
- src/input/source/iio.rs
- src/input/source/iio/bmi_imu.rs
- Adds buffer reading to BMI IIO deivce to ensure the command queue doesn't overflow and hand the driver.
- Uses try_send instead of send().await to ensure an improperly implemented driver cannot block the main thread.
> fix(CompositeDevice): Properly clear BMI source device command queue.

- rootfs/usr/share/inputplumber/devices/50-ayaneo_2.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_1s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_flip.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_kun.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_next.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_slide.yaml
> fix(Ayaneo): Add gyro support for all current AYANEO models.

- rootfs/usr/share/inputplumber/devices/50-ayn_loki.yaml
> fix(Ayn): Add gyro support for all current AYN models.

- rootfs/usr/share/inputplumber/devices/50-aokzoe_a1.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_2.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_amd.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_mini_a07.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_mini_pro.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_onexfly.yaml
> fix(OXP): Add gyro support for all current OneXPlayer models.

- rootfs/usr/share/inputplumber/devices/50-gpd_win3.yaml
- rootfs/usr/share/inputplumber/devices/50-gpd_win4.yaml
- rootfs/usr/share/inputplumber/devices/50-gpd_winmax2.yaml
- rootfs/usr/share/inputplumber/devices/50-gpd_winmini.yaml
> fix(GPD): Add gyro support for all current GPD models.

- src/udev/mod.rs
> fix(udev): conditionally use /usr/bin/chmod for device hiding

- rootfs/usr/share/inputplumber/profiles/default.yaml
- rootfs/usr/share/inputplumber/schema/device_profile_v1.json
- src/config/mod.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/source/evdev.rs
- src/input/source/hidraw.rs
- src/input/source/hidraw/lego.rs
- src/input/source/hidraw/steam_deck.rs
- src/input/source/iio.rs
- src/input/source/iio/iio_imu.rs
- src/input/target/dbus.rs
- src/input/target/dualsense.rs
- src/input/target/gamepad.rs
- src/input/target/keyboard.rs
- src/input/target/mod.rs
- src/input/target/mouse.rs
- src/input/target/steam_deck.rs
- Add create target device
- Add attach target device
- Add set target device
- Add profile config for setting target input devices
> feat(CompositeDevice): add interface to set target devices at runtime

- rootfs/usr/share/inputplumber/profiles/default.yaml
> fix(Default Profile): don't map back paddles to stick buttons by default

- src/input/target/dualsense.rs
- While at it, expose all used paddle capabilities and sort capabilities.
> fix(dualsense): Swap paddle and function initiation events to user expected values.

- src/input/composite_device/mod.rs
While at it, rename some functions to be more clear on their purpose
> fix(Intercept Mode): Fix using chords when intercept activation is one capability long

- src/dbus/interface/source/iio_imu.rs
- src/dbus/interface/source/mod.rs
- src/drivers/iio_imu/driver.rs
- src/drivers/iio_imu/info.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/source/evdev.rs
- src/input/source/hidraw/steam_deck.rs
- src/input/source/iio.rs
- src/input/source/iio/iio_imu.rs
- src/input/source/mod.rs
> feat(IIO IMU): Allow setting sample rate and scale for IMU devices.

- src/input/composite_device/mod.rs
- src/input/manager.rs
> Revert "fix(Set Target Devices): Add workaround when starting new target devices"

- src/input/target/dbus.rs
This change fixes issues where some dpad events would send "up" events too early, because dpad events would share the same button state as axis events.
> fix(DBusTarget): handle dpad events separately from axis events

- rootfs/usr/share/inputplumber/devices/50-rog_ally.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally_x.yaml
- src/drivers/rog_ally/driver.rs
> fix(ROG Ally/X): Support latest ally patches.

- .releaserc.yaml
- pkg/rpm/inputplumber.spec
RPM spec based on this by @jlobue10
https://github.com/jlobue10/ALLY_Nobara_stuff/blob/main/inputplumber.spec
> chore(RPM): add RPM spec based on work by jlobue10

- rootfs/usr/share/inputplumber/profiles/default.yaml
- src/input/target/dualsense.rs
- While at it, map Mute/Screenshot in DS5 target.
> fix(Default Profile): Adjust default profile.

- rootfs/usr/share/inputplumber/capability_maps/anbernic_type1.yaml
- rootfs/usr/share/inputplumber/devices/50-anbernic_win600.yaml
sys_vendor value is initial caps on both of my units.  Unless there are some units that report differently?
> Update sys_vendor for Win600

- src/input/composite_device/mod.rs
- src/input/target/client.rs
- src/input/target/command.rs
- src/input/target/mod.rs
- src/input/target/mouse.rs
> fix(TargetMouse): clear mouse state when intercept mode is activated

- rootfs/usr/share/inputplumber/devices/50-anbernic_win600.yaml
- rootfs/usr/share/inputplumber/devices/50-aokzoe_a1.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2021.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_kun.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_next.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_max.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_mini_pro.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_zero.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_2.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_amd.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_intel.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_mini_a07.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_mini_pro.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_onexfly.yaml
> fix(target_devices): Device driver updates

- .gitignore
- CONTRIBUTING.md
Following #247 I excluded .vscode directory to avoid risking adding my config again and added a CONTRIBUTING.md file with a few rules and suggestions.
> Contributing guidelines and IDE files exclusion

- src/input/target/mod.rs
- Fixes a bug where events would be dropped very frequently.
> fix(Horipad Steam): Increase poll rate on Horipad Steam

- rootfs/usr/share/inputplumber/devices/50-msi_claw8.yaml
IMU is currently unavailable
need udev hwdb https://github.com/systemd/systemd/pull/36180
> fix(MSI Claw 8):Add support for MSI Claw 8.

- .github/workflows/release.yaml
> chore(CI): remove inputplumber-git aur updating

- rootfs/usr/share/inputplumber/devices/50-rog_ally.yaml
- rootfs/usr/share/inputplumber/schema/composite_device_v1.json
- src/config/mod.rs
- src/dbus/interface/source/led.rs
- src/dbus/interface/source/mod.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/source/led.rs
- src/input/source/led/multicolor_chassis.rs
- src/input/source/mod.rs
- src/udev/device.rs
This PR includes @NeroReflex 's  LED implementation from #268 with review fixes so we can try to merge this in.
> Implement LEDs devices (Updated)

- src/config/mod.rs
This change modifies the `get_matching_device()` method for composite device configs to return the first source device configuration it finds in the list. The previous behavior would search for udev matches first, then evdev, hidraw, etc., which could cause issues if there are two source device configs that might match the same device.
For example, with this config:
```yaml
source_devices:
- group: gamepad
evdev:
name: Microsoft X-Box 360 pad
- group: gamepad
blocked: true
udev:
properties:
- name: ID_INPUT_JOYSTICK
value: "1"
subsystem: input
```
The old behavior would match the `udev` config first, causing the gamepad to be blocked, instead of matching the first `evdev` config.
The new behavior will now respect the source device order, so it will use the first source device config it …
> fix(Device Config): return the first matching source device config when matching sources

- src/input/target/steam_deck.rs
- Allows SDL to identify specific handhelds while using the Steam Deck target device.
- Currently only the Lenovo Legion Go and Go S, ASUS ROG Ally and Ally X, and Zotac Zone have supported PIDs.
```
$ lsusb -v -d 28de:12ff
Bus 011 Device 002: ID 28de:12ff Valve Software Legion Go S Controller
Negotiated speed: High Speed (480Mbps)
Device Descriptor:
bLength                18
bDescriptorType         1
bcdUSB               2.00
bDeviceClass            0 [unknown]
bDeviceSubClass         0 [unknown]
bDeviceProtocol         0 
bMaxPacketSize0        64
idVendor           0x28de Valve Software
idProduct          0x12ff Legion Go S Controller
bcdDevice            3.00
iManufacturer           1 Lenovo
iProduct                2 Legion Go S Controller
iSerial                 0 
bNumConfigurations …
```
> feat(Steam Deck Target): Enable setting a config for Steam Deck Target

- src/input/manager.rs
This change adds a whitelist of virtual devices that InputPlumber can manage. Namely Sunshine virtual gamepads to allow sunshine/moonlight streaming.
In the future, we may want to move this whitelist into a configuration file.
> fix(Manager): add whitelist to manage specific virtual devices

- src/dbus/interface/manager.rs
- src/input/manager.rs
This change updates the `Manager` and `ManagerInterface` to emit dbus signals whenever the gamepad order has changed. It also caches the gamepad order in the `ManagerInterface`, so dbus queries do not need to communicate with the `Manager` directly to get the current gamepad order.
In the future we should try to follow this pattern of caching data in the dbus interface struct so queries to dbus do not affect the performance of the underlying implementation. i.e. before caching, a client could send a bunch of dbus requests to get the gamepad order which the `Manager` would need to handle, which would block it from doing other work to process those requests.
> fix(Manager): emit gamepad order changed signal on order change

- .github/workflows/test.yaml
- .releaserc.yaml
- Dockerfile
- Makefile
- pkg/archlinux/PKGBUILD
This change updates the CI to include arm64 builds of InputPlumber.
> fix(CI): add build steps for arm64

- rootfs/usr/lib/systemd/system/inputplumber.service
Make systemd aware of the service being a dbus service.
> feat(systemd): flag the service as dbus type

- rootfs/usr/share/inputplumber/capability_maps/logitech_dualaction.yaml
- rootfs/usr/share/inputplumber/devices/60-LogitechDualAction.yaml
Adds YAML files for Logitech Dual Action controllers using DInput
> Support for Logitech Dual Action controllers

- rootfs/usr/share/inputplumber/devices/50-zotac-zone.yaml
This will add the G1A1W prototype we are working on.
> fix(Zotac ZONE): add G1A1W model

- src/input/composite_device/mod.rs
If a source device is removed and later added back, the force feedback effect map can get out of sync with the device state. The removed device's state needs to be deleted from the objects referencing it.
Fixes #255
> fix(CompositeDevice): Free force feedback effects on device remove

- src/input/manager.rs
When the `ManagerCommand::TargetDeviceStopped` event occurs, the `Manager` will query the `CompositeDevice` for its suspended state to determine the correct gamepad order. When it does this, it stops processing all other events and waits for a response from the `CompositeDevice`. If the `CompositeDevice`, in turn, is _also_ waiting on a response from the `Manager`, a deadlock will occur where each is waiting forever from a response from each other.
This change moves the logic where the `Manager` waits for a response from the `CompositeDevice` into a separate task so it will not block the `Manager` from processing other events. 
> [!IMPORTANT]
> One possible side effect of this change is that it's possible that other `Manager` events could occur that mutate the gamepad order before the …
> fix(Manager): get suspended state asyncronously in determining gamepad order to prevent deadlock

- rootfs/usr/share/inputplumber/devices/50-legion_go.yaml
- src/drivers/lego/driver_dinput_combined.rs
- src/drivers/lego/driver_dinput_split.rs
- src/drivers/lego/driver_fps_mode.rs
- src/drivers/lego/driver_xinput.rs
- src/input/source/hidraw.rs
These were changed in a recent controller firmware update.
> fix: Add new PIDs for Legion Go

- src/input/manager.rs
- InputManager does not use the same device queue process when starting a composite device that we use for setting the target devices after it is started. If an external process connects to the dbus interface and uses set_target_devices before the InputManager has finished starting all targets it can pass all checks against de-duplication and start multiple conflicting targets. As a remedy, instead of doing a custom one off method at init, grab the ComposteDeviceClient and set the target devices the same way.
Tested on Legion Go S and Ally X, SteamOS.
> fix(InputManager): Fix duplicate target creation.

- rootfs/usr/lib/udev/hwdb.d/60-inputplumber-autostart.hwdb
- rootfs/usr/share/inputplumber/capability_maps/ayaneo_type7.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_3.yaml
> Fix(Hardware Support): Add AYANEO 3 support.

- rootfs/usr/lib/udev/hwdb.d/60-inputplumber-autostart.hwdb
- rootfs/usr/share/inputplumber/capability_maps/onexplayer_type6.yaml
- rootfs/usr/share/inputplumber/devices/50-onexplayer_g1.yaml
> feat(Hardware Support): Add OneXPlayer G1

- src/input/target/dbus.rs
This change implements the `clear_state()` method for target dbus devices which will send "release" events for any buttons that are "pressed" when `clear_state()` is called. Normally the state is cleared whenever the user switches input profiles or when intercept mode is activated/deactivated.
> fix(Target DBus): implement clear state for dbus devices

- src/dbus/polkit.rs
Small improvement to new polkit logic.
> fix(polkit): check feature flag before creating new dbus connection
