- rootfs/usr/share/inputplumber/profiles/default.yaml
- src/input/composite_device/mod.rs
- Add default configuration for steam that covers 99% of handhelds.
> fix(CompositeDevice): Ensure proper handling of chord events in a way steam can understand them.

- src/input/manager.rs
- src/watcher/mod.rs
Attempting to watch directories that don't exist (i.e. /sys/bus/iio) crashes the system. Don't do that.
> fix(watcher): Only watch directories that exist.

- src/input/capability.rs
- src/input/composite_device/mod.rs
- Adds new function, direct_write, to the Composite Device DBus interface. This allows a third party program to bypass the translation layers when responding to DBus input events.
- Completed all pathways for Capability::from_str().
> feat(CompositeDevice): Add direct write to dbus interface of CompositeDevices

- src/input/composite_device/mod.rs
- src/input/manager.rs
- Only checks intercept mode events that are of the 'Button' sub-type for keyboard, gamepad, and mouse. Axis events are now ignored.
- Move logging for IIO finding into the proper location.
> fix(CompositeDevice): Ensure non-button events such as gyro do not break intercept mode checking.

- rootfs/usr/share/inputplumber/devices/50-orangepi_neo.yaml
The OrangePi Neo uses the BMI260 motion sensor
https://www.bosch-sensortec.com/products/motion-sensors/imus/bmi260/
> fix(OrangePi): Add correct IMU chip

- Cargo.toml
- Makefile
- rootfs/usr/lib/systemd/system/inputplumber-resume.service
Wacky way of working around a suspend issue. Partially solves #77 but should be revisited for a proper solution.
> fix(Suspend): Add restart service for InputPlumber after resume.

- src/input/composite_device/mod.rs
This fixes a crash when dynamically loading an input profile at runtime. We previously used `send_blocking`, which will crash if called from an async context (which is what we do when we receive a `LoadProfile` from DBus):
To resolve this, we now spawn an async task to send the `SetTargetDevices` command to the Composite Device.
> fix(CompositeDevice): use async task to set target devices on profile load to prevent crash

- rootfs/usr/share/inputplumber/devices/50-switch_pro.yaml
The Switch Pro controller does not create a `js*` handler, so the normal Gamepad catch-all profile does not pick up the controller. This adds a basic profile to allow managing a Switch Pro controller. In the future, we'll need to figure out a way to support the IMU half of the device.
> fix(Controller): add device profile for Switch Pro controller

- src/dbus/interface/composite_device.rs
- src/dbus/interface/manager.rs
- src/dbus/interface/mod.rs
- src/dbus/interface/source/evdev.rs
- src/dbus/interface/source/hidraw.rs
- src/dbus/interface/source/mod.rs
- src/dbus/interface/target/gamepad.rs
- src/dbus/interface/target/keyboard.rs
- src/dbus/interface/target/mod.rs
- src/dbus/interface/target/mouse.rs
- src/dbus/mod.rs
- src/lib.rs
- src/main.rs
This change moves all of the DBus interface code into their own separate files (and updates it to zbus 4.x format). This can let us re-use various DBus interfaces multiple times. Such as using a single interface for `org.shadowblip.Input.Gamepad` across all target devices.
> fix(DBus): seperate DBus interfaces into their own module

- rootfs/usr/share/inputplumber/devices/50-ayaneo_2.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_1s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_flip.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_kun.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_slide.yaml
- rootfs/usr/share/inputplumber/profiles/default.yaml
- While at it, fix some ayaneo controllers intitially reporting as a Nintendo Co., Ltd. Pro Controller.
> fix(Profiles): Use translated version of osk/quick2 instead.

- rootfs/usr/share/inputplumber/schema/composite_device_v1.json
- src/config/mod.rs
- src/input/manager.rs
This change adds a new configuration parameter called `ignore` to create configurations for stopping InputPlumber from managing a specific source device.
> feat(Manager): add config to ignore source devices from being managed

- Cargo.toml
- src/config/mod.rs
- src/dbus/interface/composite_device.rs
- src/dbus/interface/manager.rs
- src/dbus/interface/source/evdev.rs
- src/dbus/interface/source/hidraw.rs
- src/dbus/interface/target/keyboard.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/source/mod.rs
- src/input/target/dbus.rs
- src/input/target/dualsense.rs
- src/input/target/gamepad.rs
- src/input/target/keyboard.rs
- src/input/target/mouse.rs
- src/input/target/steam_deck.rs
- src/procfs/device.rs
- src/udev/device.rs
Additional changes:
* Update zbus to v4.2.2
* Better support for detecting virtual devices
* Add methods to `SourceDevice` enum to reduce code duplication
* Increase manager command buffer size
* Prevent target device changes while target devices are still waiting to be attached to a CompositeDevice
> fix(CompositeDevice): resolve deadlock issues with switching profiles

- rootfs/usr/share/inputplumber/devices/50-onexplayer_amd.yaml
My personal Onexplayer AMD was being matched as an intel model and had incorrect mappings. This fixes it.
> Fix Onexplayer AMD being recognized as intel model

- Cargo.toml
- src/config/mod.rs
- src/dmi/mod.rs
- src/input/manager.rs
The `cpu_vendor` config option existed, but we were not checking it against the system's cpu.
> fix(Config): add matching on CPU vendor id

- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus_mendo.yaml
The device uses the same capability map as Air 1S and alike.
Tested and worked for me. Now the ayaneo button opens the left-hand-side menu.
> Seperate Air Plus Mendocino, because it uses a different capability map

- src/input/composite_device/mod.rs
- src/input/manager.rs
- If a dualsense HIDRAW interface is still present when a new one is started, since the 'unique' ID is the same, the kernel driver will close the HIDRAW interface after the new device has started, orphaning the dbus interface. This change waits for the HIDRAW interfaces to close before starting the new target devices.
Fixes #113
> fix(Set Target Devices): Add workaround when starting new target devices

- src/input/composite_device/mod.rs
- src/input/manager.rs
If a dualsense HIDRAW interface is still present when a new one is started, since the 'unique' ID is the same, the kernel driver will close the HIDRAW interface after the new device has started, orphaning the dbus interface. This change waits for the HIDRAW interfaces to close before starting the new target devices.
> fix(Set Target Devices): Add workaround when starting new target devices.

- rootfs/usr/share/inputplumber/devices/60-ps4_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_360_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_one_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/69-ignore_generic.yaml
- We should ignore anything we don't have a specific configuration for until we have more implementations for unusual devices. This will prevent loads of bug reports of controllers not working.
> fix(devices): Ignore devices that aren't specified.

- src/input/composite_device/mod.rs
- src/input/source/evdev.rs
Sync events do not need to be processed. All target devices submit a sync event with every emitted event and processing them adds overhead to emitting an superflous event. Block them instead.
> fix(Capability): Block Sync events

- Cargo.toml
- src/input/composite_device/mod.rs
- src/input/target/dualsense.rs
- Avoids collisions when one device is starting up and another is shutting down.
replaces #127
> fix(DualSense): Use random mac_addr for dualsense.

- rootfs/usr/share/inputplumber/devices/50-legion_go.yaml
- src/input/source/iio.rs
- src/input/source/iio/accel_gyro_3d.rs
- src/input/source/iio/bmi_imu.rs
- Adds accel_gyro_3d implementation of IIO IMU driver. This implementation doesn't support setting scale or sample frequency and has a different scaling factor for the gyro and accelerometer than BMI devices.
- Renames IIO IMU to BMI IMU for disabiguation and improves debug statements.
- Adds mount matric for LegionGo display IMU.
> fix(LegionGo): Add accel_gyro_3d implementation for IIO IMU driver.

- src/dbus/interface/composite_device.rs
- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/source/evdev.rs
- src/input/source/hidraw.rs
- src/input/source/hidraw/fts3528.rs
- src/input/source/hidraw/lego.rs
- src/input/source/hidraw/opineo.rs
- src/input/source/hidraw/steam_deck.rs
- src/input/source/iio.rs
- src/input/source/iio/accel_gyro_3d.rs
- src/input/source/iio/bmi_imu.rs
- src/input/target/dbus.rs
- src/input/target/dualsense.rs
- src/input/target/gamepad.rs
- src/input/target/keyboard.rs
- src/input/target/mod.rs
- src/input/target/mouse.rs
- src/input/target/steam_deck.rs
- src/input/target/touchscreen_fts3528.rs
- src/input/target/xb360.rs
This change adds a new `CompositeDeviceClient` to simplify communicating with a `CompositeDevice`. It provides helper methods for sending and receiving data over a channel.
For example, instead of doing:
```rust
tx.send(Command::ProcessEvent(device_id, event).await?;
```
we can now do:
```rust
composite_device.process_event(device_id, event).await?;
```
This is especially helpful when getting data back from a composite device.
> refactor(CompositeDevice): add CompositeDeviceClient

- rootfs/usr/share/inputplumber/devices/50-ayn_loki_max.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_mini_pro.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_zero.yaml
- src/drivers/iio_imu/driver.rs
- src/input/composite_device/mod.rs
- src/input/source/evdev.rs
- src/input/target/dbus.rs
- src/input/target/dualsense.rs
- src/input/target/keyboard.rs
- src/input/target/mod.rs
- src/input/target/mouse.rs
- src/input/target/steam_deck.rs
- src/input/target/touchscreen_fts3528.rs
- src/input/target/xb360.rs
- src/input/target/xbox_elite.rs
- Reduces the poll rate for evdev source devices and gyro's to 125Hz. Disables gyro on low power devices (AYANEO AIR, AYN Loki Zero).
- Adds fix for bugs caused by stopping/starting the same target device type. We no longer stop a running device if it is requested to start.
> fix(Performance): Reduce poll rate for most source devices.

- src/dbus/interface/source/iio_imu.rs
- src/input/composite_device/mod.rs
- src/input/source/client.rs
- src/input/source/command.rs
- src/input/source/evdev.rs
- src/input/source/hidraw.rs
- src/input/source/iio.rs
- src/input/source/mod.rs
This change, like #133 adds a new `SourceDeviceClient` to simplify communicating with a `SourceDevice`. It provides helper methods for sending and receiving data over a channel.
For example, instead of doing:
```rust
tx.send(SourceCommand::WriteEvent(event).await?;
```
we can now do:
```rust
source_device.write_event(event).await?;
```
> refactor(SourceDevice): implement source device client for channel communication

- src/dbus/interface/target/keyboard.rs
- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/target/client.rs
- src/input/target/command.rs
- src/input/target/dbus.rs
- src/input/target/dualsense.rs
- src/input/target/keyboard.rs
- src/input/target/mod.rs
- src/input/target/mouse.rs
- src/input/target/steam_deck.rs
- src/input/target/touchscreen_fts3528.rs
- src/input/target/xb360.rs
- src/input/target/xbox_elite.rs
- src/input/target/xbox_series.rs
This change, like #133 and #142  adds a new `TargetDeviceClient` to simplify communicating with a `TargetDevice`. It provides helper methods for sending and receiving data over a channel.
For example, instead of doing:
```rust
tx.send(TargetCommand::WriteEvent(event).await?;
```
we can now do:
```rust
target_device.write_event(event).await?;
```
> refactor(TargetDevice): implement target device client

- rootfs/usr/share/inputplumber/capability_maps/msiclaw_type1.yaml
- rootfs/usr/share/inputplumber/devices/50-msi_claw.yaml
Adds initial support for the MSI Claw. 
Currently relies on udev rules and hwdb updates found in https://github.com/ChimeraOS/device-quirks
hwdb entry has been pushed upstream. xpad patch has not been upstreamed yet.
> fix(MSI Claw): Add support for MSI Claw.

- rootfs/usr/share/inputplumber/schema/device_profile_v1.json
- src/config/mod.rs
- src/input/capability.rs
This change adds two new config entries for input profiles: `touchpad` and `touchscreen`.
To add these translations, I had to:
* Update the `CapabilityConfig` struct with the new translation config
* Update the device profile schema with the new config fields
* Update `From<CapabilityConfig> for Capability` to convert a translation config into a capability
* Update `InputValue::translate` to translate the input value to the target
> feat(Touch): add basic touch input translation support

- rootfs/usr/share/inputplumber/devices/60-ps5_ds-edge_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-ps5_ds_gamepad.yaml
This change adds basic device profiles for the DS5/DS5 Edge gamepads for InputPlumber (i.e. without gyro or touch support). Full support will be added in a subsequent PR with an HIDRaw driver implementation.
> fix(PS5): add basic support for DS5/DS5-Edge gamepads

- src/dbus/interface/manager.rs
- src/input/manager.rs
- src/input/target/mod.rs
This change adds a new `TargetDeviceTypeId` type to easily enforce a list of valid target device id strings, and adds the `SupportedTargetDevices` and `SupportedTargetDeviceIds` properties to the Manager DBus interface. This can allow dbus clients to query for supported target devices:
```bash
$ busctl get-property org.shadowblip.InputPlumber /org/shadowblip/InputPlumber/Manager org.shadowblip.InputManager SupportedTargetDeviceIds
as 12 "null" "dbus" "keyboard" "mouse" "gamepad" "touchscreen" "xb360" "xbox-elite" "xbox-series" "deck" "ds5" "ds5-edge"
```
```bash
$ busctl get-property org.shadowblip.InputPlumber /org/shadowblip/InputPlumber/Manager org.shadowblip.InputManager SupportedTargetDevices
as 12 "Null Device" "DBus Device" "InputPlumber Keyboard" "InputPlumber Mouse" "InputPlumber …
```
> feat(Manager): add dbus properties to view supported target devices

- Cargo.toml
- rootfs/usr/share/inputplumber/devices/50-legion_go.yaml
- rootfs/usr/share/inputplumber/devices/50-orangepi_neo.yaml
- rootfs/usr/share/inputplumber/devices/50-steam_deck.yaml
- rootfs/usr/share/inputplumber/profiles/default.yaml
- src/drivers/opineo/driver.rs
- src/drivers/opineo/hid_report.rs
- src/drivers/steam_deck/hid_report.rs
- src/input/composite_device/mod.rs
- src/input/event/native.rs
- src/input/manager.rs
- src/input/source/hidraw/opineo.rs
- src/input/target/dbus.rs
- src/input/target/dualsense.rs
- src/input/target/keyboard.rs
- src/input/target/mod.rs
- src/input/target/mouse.rs
- src/input/target/steam_deck.rs
- src/input/target/touchscreen.rs
- src/input/target/xb360.rs
- src/input/target/xbox_elite.rs
- src/input/target/xbox_series.rs
- src/udev/device.rs
Tested with Sony DualSense source device.
> feat(SteamDeckTarget): add Steam Deck Controller target device through USB emulation

- src/input/composite_device/mod.rs
- src/input/source/client.rs
- src/input/source/evdev/gamepad.rs
- src/input/source/mod.rs
- src/input/target/xb360.rs
- src/input/target/xbox_elite.rs
- src/input/target/xbox_series.rs
This fixes a bug where the target device would stop if an error occurred when uploading a force feedback event to source devices. Force feedback uploads are non-fatal now.
> fix(ForceFeedback): add default implementation for FF that does not error

- src/input/event/dbus.rs
- src/input/target/dbus.rs
This change enables analog trigger input translation to DBus events. Previously only binary trigger input would be translated. This change will also ignore binary trigger events if analog trigger input is detected in the case that an input device supports both binary and analog trigger input.
> fix(DBusTarget): translate analog trigger input to dbus events

- src/drivers/rog_ally/driver.rs
Case sensitivity update (to all caps) for the button remapping fixes the back buttons to working status again for ASUS ROG ALLY and ROG ALLY X (with latest kernel patches from Luke Jones).
> Fix back buttons for ASUS ROG ALLY and ROG ALLY X

- src/dbus/interface/target/mouse.rs
- src/input/target/mouse.rs
This change adds the `MoveCursor` method to the mouse DBus interface to allow mouse control over DBus.
> feat(TargetMouse): add MoveCursor method to virtual mouse interface

- src/drivers/rog_ally/driver.rs
When resuming from sleep, if mcu_powersave is set, the device init takes longer. inotify will trigger the Ally driver before the attribute tree is fully built and the driver will error and exit, leaving some controls unusable. This is a temporary workaround to support releasing a hotfix release ASAP. We should find a way to only trigger the driver or continue processing it only after we know the driver has fully init.
> fix(ROG Ally/X): Wait for driver init

- src/drivers/xpad_uhid/driver.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/watcher/mod.rs
When connecting an XBox Series controller using bluetooth, this behavior was observed:
```
[2024-08-19T19:33:06Z DEBUG inputplumber::watcher] inotify CREATE: Some("hidraw4")
[2024-08-19T19:33:06Z DEBUG inputplumber::watcher] inotify DELETE: Some("hidraw4")
[2024-08-19T19:33:06Z DEBUG inputplumber::watcher] inotify CREATE: Some("hidraw4")
```
This would ultimately result in the `CompositeDevice` stopping when it received the `DELETE` event because no source devices would remain.
Normally this would be fine, and we'd expect the second `CREATE` event to create a new `CompositeDevice`. But because the input `Manager` and `CompositeDevice` run as separate tasks, processing at different speeds, we'd run into a situation where the `CompositeDevice` has not had a chance to actually stop before …
> fix(XPad Bluetooth): resolve race condition if a device is quickly added, removed, and added again

- src/dbus/interface/source/evdev.rs
- src/dbus/interface/source/mod.rs
- src/dbus/interface/source/udev.rs
- src/input/manager.rs
- src/input/source/evdev.rs
- src/udev/device.rs
This change exposes source evdev device capabilities over DBus, providing an interface for applications to query what kind of input devices are connected and what they are capable of (i.e. checking if a keyboard is plugged in). The values returned are in the form of Linux event codes that the device supports.
This change also exposes udev properties over DBus:
> feat(Evdev): expose source device capabilities over dbus

- Makefile
This change updates the systemd extension builds so the extension can be used on any distribution. Note that `ID=_any` is only available on systems with systemd v252+.
> fix(Systemd Extension): use 'ID=_any' to load on any OS variant

- rootfs/usr/share/inputplumber/capability_maps/gpd_type3.yaml
- rootfs/usr/share/inputplumber/devices/50-gpd_win4.yaml
Fix back buttons on the GPD Win 4
tested on the GPD Win 4 6800u
OS: Bazzite
InputPlumber version: inputplumber-0.35.2
> fix(gpd_win4): fix back buttons

- src/config/path.rs
This change reverses the load order of capability maps, so configs in `/etc` can be used to override ones defined in `/usr/share`.
> fix(Capability Map): reverse load order to override capability map

- rootfs/usr/share/inputplumber/devices/50-ayaneo_2.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_1s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus_mendo.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_flip.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_slide.yaml
InputPlumber maps LC and RC to LeftPaddle1 and RightPaddle1, respectively.  However, Ayaneo devices are set to xb360 and cannot take advantage.
This changes tested Ayaneo devices to xbox-elite.  Air Plus Mendo and Kun are untested and are not included.
> Change some Ayaneo devices to xbox-elite

- src/input/target/dualsense.rs
- src/input/target/xb360.rs
- src/input/target/xbox_elite.rs
- src/input/target/xbox_series.rs
Occasionally, pushing the QAM button may have SteamOS process the emitted Guide and A button outputs in the incorrect order (eg pressing A and then opening the Steam menu).  This seems to occur more often on devices that do not support holding the QAM output (such as ROG Ally and MSI Claw).
This changes the Guide button to be held an extra 80ms before emitting A.  In my testing I failed to see a single aberrant event once this change was applied.  Testing was performed on MSI Claw, Win600, ROG Ally and Ayaneo Air Plus.
> fix(target): Adjust QAM chord timing

- .github/workflows/release.yaml
This change removes publishing the `inputplumber` AUR package as it has now landed in stable and also includes GPG signing of commits and tags.
> chore(CI): remove redundant AUR publish and add GPG signing

- src/input/composite_device/mod.rs
This only affects some devices that poll both axis at the same time. This triggered only left and right events completely ignoring y axis.
> fix(CompositeDevice): allow multiple mappings to be applied for an event

- src/dbus/interface/manager.rs
This change adds the `Version` property to the manager interface to expose the running InputPlumber version.
> feat(Manager): expose InputPlumber version over dbus

- src/drivers/dualsense/driver.rs
- src/drivers/dualsense/hid_report.rs
I hate this solution. 
If anyone has better idea on how to solve this, please please bring it up.  
Closes #230
This essentially moves logic for releasing buttons after the logic that maps button pressed events.
The logic especially handles transitions between in-between states like `NorthEast -> East` - this will release a North button.
> fix(ds5): dpad getting "stuck"

- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- pkg/rpm/inputplumber.spec
- rootfs/usr/lib/systemd/system/inputplumber-suspend.service
- src/dbus/interface/manager.rs
- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/target/steam_deck.rs
This change adds new `HookSleep` and `HookWake` dbus methods that can be called by a systemd unit on suspend/resume to allow InputPlumber to prepare for sleep/wake. It also includes the latest version of the `virtual-usb` crate which contains a fix where the read/write threads of the virtual usb device would fail to stop, leaving a dangling virtual usb device.
This change seems to be required due to the appearance that the virtual usb kernel driver currently does not support suspend:
https://github.com/torvalds/linux/blob/master/drivers/usb/usbip/vhci_hcd.c#L1260
In order for this feature to work, users will need to ensure the suspend systemd unit is also enabled for InputPlumber:
```bash
sudo systemctl enable inputplumber-suspend
```
Fixes #165
> feat(Manager): add suspend/wake hook methods to handle reconnecting Deck target device

- rootfs/usr/share/inputplumber/devices/60-xbox_one_bt_gamepad.yaml
- rootfs/usr/share/inputplumber/schema/composite_device_v1.json
- src/config/mod.rs
- src/drivers/xpad_uhid/driver.rs
- src/input/manager.rs
- src/input/source/evdev/blocked.rs
- src/input/source/hidraw.rs
- src/udev/device.rs
This change adds the ability to match source devices in composite device configs based on udev properties. This new matching method is the most powerful and flexible way to match input devices and could completely replace the existing `evdev`, `hidraw`, and `iio` match configs, but those methods will still exist to maintain backwards compatibility.
Here are some examples:
```yaml
source_devices:
- group: gamepad
hidraw:
vendor_id: 0x054c
product_id: 0x0ce6
- group: gamepad
blocked: true
evdev:
name: "{Sony Interactive Entertainment DualSense Wireless Controller,DualSense Wireless Controller}"
vendor_id: 054c
product_id: 0ce6
handler: event*
```
```yaml
source_devices:
- group: gamepad
udev:
attributes:
- name: "idVendor"
value: "054c"
- name: "idProduct"
value: "0ce6"
subsystem: "hidraw" …
```
> feat(CompositeDeviceConfig): add udev-based source device matching

- src/input/composite_device/mod.rs
This change will clear the state of all target devices whenever the input profile changes on a composite device. This fixes an issue where if a user had an input profile with joystick -> mouse translation and the profile changed to one without that translation, the virtual mouse would continue to send input.
> fix(CompositeDevice): clear state for target devices on profile change

- rootfs/usr/share/inputplumber/devices/50-gpd_winmini.yaml
This mount matrix felt right on the Win Mini 2023 playing games through Steam Input with the ds5 selected.
I've heard the 2024 has the same DMI device entries but may have the IMU mounted differently -- not sure what could be done about that.
> fix(GPD): Add mount matrix for GPD Win Mini

- rootfs/usr/share/inputplumber/devices/50-ayaneo_2.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2021.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_1s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_air_plus_mendo.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_flip.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_next.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_max.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_mini_pro.yaml
- rootfs/usr/share/inputplumber/devices/50-ayn_loki_zero.yaml
- rootfs/usr/share/inputplumber/devices/50-gpd_win4.yaml
- rootfs/usr/share/inputplumber/devices/50-legion_go.yaml
- rootfs/usr/share/inputplumber/devices/50-msi_claw.yaml
- rootfs/usr/share/inputplumber/devices/50-orangepi_neo.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally_x.yaml
~~WIP.  Still gathering device data.~~
> fix(mount_matrix): Update gyro matrices

- rootfs/usr/share/inputplumber/capability_maps/ayaneo_type4.yaml
Add support for Secondary Screen Interaction button on Flip DS.  Currently mapped to Keyboard.
> feat(Flip DS): Add SSI button as OSK

- rootfs/usr/share/inputplumber/capability_maps/msiclaw_type1.yaml
System/Menu buttons are inverted.
More info: https://github.com/ShadowBlip/InputPlumber/issues/250
> Fix inverted MSI-Claw menu buttons

- rootfs/usr/share/inputplumber/devices/60-ps4_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-ps5_ds-edge_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-ps5_ds_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-switch_pro.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_360_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_one_elite_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-xbox_one_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/69-ignore_generic.yaml
- rootfs/usr/share/inputplumber/devices/70-generic_gamepad.yaml
This change updates all external gamepad configs to use the new `maximum_sources` config option instead of `single_source`. This fixes an issue for some gamepads (like the DualSense controller) where a single CompositeDevice would capture all detected controllers of the same type instead of creating a new CompositeDevice.
> fix(External Gamepads): use maximum_sources instead of single_source to allow multiple gamepads

- src/input/composite_device/mod.rs
- src/input/manager.rs
This PR improves the handling of the dbus for CompositeDevice: makes it so a dbus is required to have a CompositeDevice and in no situation the service can crash/panic by removing the .unwrap(). It also simplify the code a bit decreasing lines count.
This is also part of the saga "do not spawn tasks without returning the handle and try not to lose tasks references" albeit in this case the reference is still lost, but it is lost in manager.rs and a future code improvement can pick it up.
> fix(dbus) make dbus path parth of a CompositeDevice at construction

- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/target/mod.rs
This change adds new methods to allow target devices to query the composite device it's attached to for its configuration and source devices. This can allow us to modify the behavior of target devices based on the composite device config and/or source devices.
> fix(TargetDevice): add method for target devices to query composite device config

- src/input/composite_device/mod.rs
Closes #258
This is a proposition of a solution that addresses said issue. 
By mapping target_capability -> source_capability we can reference "ownership" of an input to given source event within the CompositeDevice. I think this change should be considered potentially breaking.
At the moment this prevents input cancellation for buttons on Gamepad, Keyboard and Mouse capabilities
> fix: avoid inputs cancelling each other

- Cargo.lock
- Cargo.toml
- src/cli/device.rs
- src/cli/mod.rs
- src/cli/source.rs
- src/cli/target.rs
- src/dbus/interface/composite_device.rs
- src/dbus/interface/manager.rs
- src/dbus/interface/source/udev.rs
- src/lib.rs
- src/main.rs
This change adds a simple command-line interface to InputPlumber to expose some basic functionality that we can expand on in the future. The new interface allows inputplumber to run as a client to execute dbus methods to provide a more user-friendly way to interact with the InputPlumber service.
```bash
$ ./inputplumber help
Open source input manager for Linux
Usage: inputplumber [COMMAND]
Commands:
run      Start the InputPlumber daemon (default)
sources  Manage source input devices
device   Manage a composite device
devices  Manage composite devices
targets  Manage target input devices
help     Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```
```bash
$ ./inputplumber devices list …
```
> feat(CLI): add command line client interface

- rootfs/usr/share/inputplumber/devices/50-ayaneo_2.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_2s.yaml
- rootfs/usr/share/inputplumber/devices/50-ayaneo_flip.yaml
- rootfs/usr/share/inputplumber/devices/50-legion_go.yaml
- rootfs/usr/share/inputplumber/devices/50-msi_claw.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally_x.yaml
- rootfs/usr/share/inputplumber/devices/50-steam_deck.yaml
- rootfs/usr/share/inputplumber/schema/composite_device_v1.json
- src/config/mod.rs
- src/input/composite_device/mod.rs
- src/input/source/evdev.rs
- src/input/source/evdev/touchscreen.rs
- src/input/target/touchscreen.rs
- src/udev/device.rs
This change adds support for generic touchscreen source devices. This change also adds the `config` section of a source device to allow defining arbitrary configuration of that captured source device. i.e. in the case of touchscreens, it can allow the source driver to translate touches based on the orientation of the touchscreen.
> feat(Touchscreen): add support for generic touchscreen devices

- rootfs/usr/share/inputplumber/schema/composite_device_v1.json
- src/config/mod.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/source/evdev.rs
- src/input/source/evdev/keyboard.rs
- src/input/source/hidraw.rs
- src/input/source/iio.rs
- src/input/source/mod.rs
- src/udev/mod.rs
This change adds two new configurable features:
- Source device event filtering - exclude processing certain events from a source device
- Source device passthrough - InputPlumber won't hide or grab exclusive access to a source device
> feat(SourceDevice): add source device event filtering and configurable device hiding

- src/cli/device.rs
- src/dbus/interface/manager.rs
- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/input/target/mod.rs
This change adds the `GamepadOrder` property to the `Manager` interface to allow users to re-order gamepads.
> feat(Manager): add gamepad reordering

- src/input/source/evdev.rs
- src/udev/device.rs
This change fixes an issue where the evdev source would not identify the correct driver to use because the udev properties to identify the driver are no longer present at the time of source device initialization. I suspect this could be from udev hiding that triggers reloading the rules.
This change caches udev properties, so they will be queryable at the time of source device initialization.
> fix(Udev): cache device properties so they are not lost during rule evaluation

- rootfs/usr/lib/systemd/system/inputplumber.service
- src/input/composite_device/mod.rs
- src/input/manager.rs
- src/udev/device.rs
- src/udev/mod.rs
This change also includes fixes for a deadlock that can occur with `SetTargetDevices` introduced by an earlier version.
> fix(CompositeDevice): move device hiding logic back to device start instead of device add

- rootfs/usr/share/inputplumber/schema/capability_map_v1.json
- src/input/event/evdev.rs
`event_codes_from_capability` already has capability -> keycodes, just adding the missing keycodes -> capability
Additionally fix the capability map schema to match the Config code and the existing capability maps.
> fix(evdev) Add in missing mapping for evdev keycodes to capabilities

- Makefile
- examples/unified_gamepad/main.rs
- rootfs/usr/lib/udev/hwdb.d/59-inputplumber.hwdb
- src/drivers/mod.rs
- src/drivers/unified_gamepad/capability.rs
- src/drivers/unified_gamepad/driver.rs
- src/drivers/unified_gamepad/event.rs
- src/drivers/unified_gamepad/mod.rs
- src/drivers/unified_gamepad/reports.rs
- src/drivers/unified_gamepad/reports/input_capability_report.rs
- src/drivers/unified_gamepad/reports/input_capability_report_test.rs
- src/drivers/unified_gamepad/reports/input_data_report.rs
- src/drivers/unified_gamepad/reports/input_data_report_test.rs
- src/drivers/unified_gamepad/value.rs
- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/target/mod.rs
- src/input/target/unified_gamepad.rs
This change adds the Unified Controller as defined by the [Unified Controller Input Spec](https://github.com/ShadowBlip/UnifiedControllerInputSpec). If used as a target device, it will create a virtual hidraw interface that will send input reports based on the source device capabilities.
> feat(Unified Controller): add unified controller driver

- Cargo.lock
- Cargo.toml
- Makefile
- rootfs/usr/share/inputplumber/profiles/debug.yaml
- src/cli/device.rs
- src/cli/mod.rs
- src/cli/ui.rs
- src/cli/ui/menu.rs
- src/cli/ui/menu/device_test_menu.rs
- src/cli/ui/widgets.rs
- src/cli/ui/widgets/axis_gauge.rs
- src/cli/ui/widgets/button_gauge.rs
- src/cli/ui/widgets/gyro_gauge.rs
- src/cli/ui/widgets/touch_gauge.rs
- src/cli/ui/widgets/trigger_gauge.rs
- src/config/mod.rs
- src/config/path.rs
- src/dbus/interface/composite_device.rs
- src/dbus/interface/target/debug.rs
- src/dbus/interface/target/mod.rs
- src/input/composite_device/mod.rs
- src/input/target/debug.rs
- src/input/target/mod.rs
- src/input/target/unified_gamepad.rs
This change adds a new input testing to the inputplumber command line interface. It uses a new `debug` target device that uses the [UCIS](https://github.com/ShadowBlip/UnifiedControllerInputSpec) standard for emitting input events, but over dbus.
You can run it with:
```bash
inputplumber device 0 test
```
where `0` is the composite device id:
[2025-02-24 20-34-26.webm](https://github.com/user-attachments/assets/1a5f603a-e7a0-4ae1-8e0c-cdd9f6e43d0c)
> feat(CLI): add input testing menu

- src/cli/ui/menu/device_test_menu.rs
- src/drivers/unified_gamepad/reports.rs
- src/drivers/unified_gamepad/reports/input_capability_report.rs
This change just fully enumerates all of the value types we plan on supporting in the spec.
> fix(Unified Gamepad): add extra value types

- src/drivers/unified_gamepad/capability.rs
- src/input/target/unified_gamepad.rs
This change adds the `GamepadButtonTopLeft` and `GamepadButtonTopRight` translations for the unified gamepad, as well as touchscreen.
> fix(Unified Gamepad): implement top buttons and touchscreen

- rootfs/usr/share/inputplumber/devices/50-orangepi_neo.yaml
- src/input/source/iio.rs
this add the BOSC0260 IIO detection. Tested on firmware set `BCPH01_V1.20_OrangePi_modoify_audio269_table` with `EC_BCPH01_V0.15`.
> fix(OrangePi NEO): Add BOSC0260 IIO detection

- rootfs/usr/share/inputplumber/devices/50-legion_go_s.yaml
- src/drivers/legos/driver.rs
- src/input/source/hidraw.rs
- Adds new name from upstream kernel patch. https://lore.kernel.org/linux-input/20250222170010.188761-4-lkml@antheas.dev/
- While at it, add support for dinput PID
> fix(Legion Go S): Fix breakage from upstream kernel changes.

- src/cli/ui/menu/device_test_menu.rs
This change cleans up the labels to strip some common prefixes and adjusts the layout to work better on smaller screens.
> fix(CLI): clean up input labels and change ui layout for smaller screens

- rootfs/usr/share/inputplumber/devices/50-msi_claw7_a2vm.yaml
- rootfs/usr/share/inputplumber/devices/50-msi_claw8_a2vm.yaml
- rootfs/usr/share/inputplumber/devices/50-msi_claw_a1m.yaml
- rootfs/usr/share/inputplumber/schema/composite_device_v1.json
- src/drivers/mod.rs
- src/drivers/msi_claw/driver.rs
- src/drivers/msi_claw/hid_report.rs
- src/drivers/msi_claw/mod.rs
- src/input/source/hidraw.rs
- src/input/source/hidraw/msi_claw.rs
This change adds support for switching the MSI Claw into XInput mode for systems that do not have kernel support. Once Nero's driver has been upstreamed to the kernel, we can update this method to use the sysfs interface when it is available.
> fix(MSI Claw): add support for setting XInput mode for systems without kernel support

- README.md
inputplumber is available in the official Arch Linux repositories, so there is no reason to prefer the AUR package over the former.
> README.md: Use repository package for install instructions

- rootfs/usr/share/inputplumber/devices/50-legion_go.yaml
- rootfs/usr/share/inputplumber/devices/50-legion_go_2.yaml
Legion Go 2 uses a same MCU but different USB PID to distinguish the model, init the support for it as translate to a Xbox Elite Controller.
Tested on Legion Go 2 sample:
[device_info.log](https://github.com/user-attachments/files/19703327/device_info.log)
[devices_list.log](https://github.com/user-attachments/files/19703328/devices_list.log)
> fix(Legion Go): Split Legion Go 2 config due to different PID to Go 1

- src/input/target/mod.rs
- src/input/target/touchpad.rs
This change fixes slowness, jitter, and overall bad feeling of virtual touchpads. An example of this can be found in the following review video:
[![ETA Prime Video](https://img.youtube.com/vi/lU9LkJYfd68/maxresdefault.jpg)](https://www.youtube.com/embed/lU9LkJYfd68?start=137&end=158)
https://www.youtube.com/embed/lU9LkJYfd68?start=137&end=158
The main change that fixed this issue was to change the polling rate of the target touchpad device from 13ms to 3ms.
> fix(Target Touchpad): use higher resolution and polling rate to fix slow, jittery touch behavior

- README.md
It seems my earlier change #334 introduced a typo here. I also took some liberties and added a whitespace between Arch and Linux.
> fix(README.md): Fix typos in Arch Linux installation instructions

- rootfs/usr/share/inputplumber/capability_maps/ally_type1.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally_x.yaml
- src/drivers/rog_ally/driver.rs
Instead of bombing out of the driver init process allow IP to keep working as the majority of parts should still be usable.
> fix(ASUS Ally): don't crash out of driver init if attrs fail

- src/input/composite_device/mod.rs
- src/input/composite_device/targets.rs
Currently the main composite device file is sitting at 2312 lines, encapsulating a _lot_ of functionality, making it difficult to work on and debug. This change refactors the `CompositeDevice` struct to pull out all target device state and handling into its own `CompositeDeviceTargets` struct.
In an upcoming PR, I also plan on doing the same for source device handling by creating a `CompositeDeviceSources` struct and moving the source device behavior there to further reduce the amount of state and behavior in `CompositeDevice`.
> fix(Composite Device): refactors target device behavior into its own struct

- pkg/rpm/inputplumber.spec
Fixes RPM build by using platform-specific binary:
https://copr.fedorainfracloud.org/coprs/shadowblip/InputPlumber/build/8979799/
> fix(RPM): update spec to use platform-specific binary

- Cargo.lock
- Cargo.toml
- rootfs/usr/share/inputplumber/devices/50-legion_go_s.yaml
- src/drivers/legos/config_driver.rs
- src/drivers/legos/mod.rs
- src/input/source/hidraw.rs
- src/input/source/hidraw/legos_config.rs
- Adds support for configuring the Legion Go S Gamepad and Touchpad devices. Depends on lenovo-legos-hid driver.
> feat(Legion Go S): Add Config Support

- Makefile
This change uses the latest available aarch64 libiio version for the systemd-extension. This fixes the build pipeline which was failing because the old version of libiio (0.26-2) is no longer available to download.
> chore(Makefile): use latest aarch64 libiio version for systemd-extension

- src/drivers/msi_claw/driver.rs
- src/drivers/msi_claw/hid_report.rs
- src/input/source/hidraw/msi_claw.rs
This change fixes an issue where sometimes the gamepad would fail to switch into xinput mode. Tested on two different devices. It will also read and print the current gamepad mode if debug logging is enabled.
> fix(MSI Claw A1M): send MKeys setting when switching to xinput mode

- src/input/target/steam_deck.rs
- src/input/target/steam_deck_uhid.rs
- Ensure only the Steam Deck is detected with the valid Steam Deck PID.
- Add generic PID so devices that are not a Deck can work with deck-uhid.
Tested on OrangePi NEO
> fix(Deck): Add generic target PID

- .github/workflows/test.yaml
- .releaserc.yaml
- Makefile
Sometimes `uname -m` does not match target triple's arch (like riscv64, which is riscv64gc-*), sometimes we don't have `gnu` but `gnueabi` or `musl`. Use the [method](https://wiki.archlinux.org/title/Rust_package_guidelines#Prepare) used on Arch Linux to directly get target triple from rustc.
> fix(Makefile): use target triple from rustc for TARGET_ARCH

- Cargo.toml
- Makefile
- pkg/rpm/inputplumber.spec
- rootfs/usr/lib/udev/hwdb.d/60-inputplumber-autostart.hwdb
- rootfs/usr/lib/udev/rules.d/90-inputplumber-autostart.rules
- Modified from steamos-customizations, the new udev hwdb and udev rules allow for automatic startup of inputplumber on boot. This allows immutable systems to ship inputplumber and not need clever hacks or a blanket service enabling when not needed. This will also improve the level of support out of the box in SteamOS.
> feat(Autostart): Add autostart rules/hwdb for InputPlumber

- rootfs/usr/share/inputplumber/devices/50-gpd_winmini.yaml
- src/input/source/iio.rs
The upstream driver has a different device name and needs to be detected using the new name.
I added `bmi260` literally because `bmi*` seemed like it could be too generic, but I'm happy to change `bmi*-imu` to `bmi*` if you'd prefer.
> fix(GPD): Support upstream gyro driver

- src/drivers/legos/mod.rs
- src/input/source/hidraw.rs
The Legion Go S Poll rates were not correct for each source device. This caused stuttering in steam's virtual menus and affected steam input's momentum calculations. Steam input treats duplicate touch events as a "stop motion" case, if the x and y have not changes for more than 1 consecutive event.
Changing these values to the correct poll rates fixes both problems and reduces CPU load.
> fix(Legion Go S): Use correct poll rates for Go S source devices.

- pkg/rpm/inputplumber.spec
Fixes COPR builds:
https://copr.fedorainfracloud.org/coprs/shadowblip/InputPlumber/builds/
> fix(RPM): add missing udev and hwdb files

- src/input/target/dbus.rs
When translating joystick axis events to DBus events, there are some cases where the hardware polling rate is so slow (i.e. Ayaneo) that a user is able to quickly move the stick so that a "release" event is never emitted. 
E.g. we receive a axis down events, then immediately get an axis up event without crossing the threshold needed to emit the "release" event for the axis down:
```
Action::Down 0.8
Action::Down 0.9
Action::Down 1.0
Action::Up   0.3
```
This change adds logic in the axis translation to always send a "release" event if any events from the opposite axis are detected.
> fix(DBus): properly emit 'release' event if opposite axis events occur

- Makefile
- src/cli/device.rs
- src/cli/ui/menu.rs
- src/cli/ui/menu/device_performance_menu.rs
- src/dbus/interface/mod.rs
- src/dbus/interface/performance.rs
- src/input/composite_device/mod.rs
- src/input/composite_device/targets.rs
- src/input/event/context.rs
- src/input/event/mod.rs
- src/input/event/native.rs
- src/input/source/mod.rs
- src/input/target/mod.rs
This change adds a new `EventContext` property of the `NativeEvent` which can hold performance metrics and metadata related to an input event. Performance metrics can be used to show the processing latency for each event.
Performance/latency can be monitored with the CLI:
```bash
inputplumber device 0 target monitor xbox-series
```
Where "xbox-series" is the target device type to monitor.
> feat(Event): add event context with performance metrics

- src/config/mod.rs
- src/input/composite_device/client.rs
- src/input/composite_device/command.rs
- src/input/composite_device/mod.rs
- src/input/info.rs
- src/input/manager.rs
- src/input/mod.rs
- src/input/source/evdev.rs
- src/input/source/hidraw.rs
- src/input/source/iio.rs
- src/input/source/led.rs
- src/input/source/mod.rs
This change is meant to be a precursor to a new version of the #307 PR to include support for network sources, as well as other non-udev based source devices.
It refactors parts of the codebase to use a new `DeviceInfo` enum instead of our previous assumption that all source devices would be udev devices.
> fix(Source Device): refactor to use DeviceInfo enum instead of UdevDevice for source device discovery

- rootfs/usr/share/inputplumber/devices/50-steam_deck.yaml
This change disables managing the touchscreen on the Steam Deck by default.
> fix(Steam Deck): don't manage touchscreen by default

- src/input/source/hidraw/dualsense.rs
the dualsense gamepad doesn't have such key and this only causes problems for apps that rely on checking for this capability
unsure how the key-combo use case of that capability behaves now (as I have not tested that), I believe however the target driver should work as expected
> fix: remove quick access capability from source dualsense

- Makefile
- rootfs/usr/share/inputplumber/devices/60-ps5_ds-edge_gamepad.yaml
- rootfs/usr/share/inputplumber/devices/60-ps5_ds_gamepad.yaml
In some cases, the DualSense wireless controller will show up as "Wireless Controller" instead of "DualSense Wireless Controller" when using older controller firmware. This change updates the name matching to match both varieties.
> fix(DualSense): adjust device matching to work with older controller firmware

- rootfs/usr/share/inputplumber/devices/50-zotac-zone.yaml
Users on SteamOS are reporting that touchpads do not work on the Zotac Zone. Steamos-manager currently only creates a deck-uhid target so the rel events produced have no target device to emit from. Passthrough the events to reintroduce this functionality. This may need to be changed in the future if touchpad firmware is updated to include an abs event mode, though it would likely have a different report descriptor and name at that point.
> Fix(Hardware Support): Passthrough Zotac Zone Touchpads

- rootfs/usr/share/inputplumber/schema/device_profile_v1.json
- src/input/event/dbus.rs
This change updates dbus events to include a new `Action::Custom` variant which can be used to send dbus events with arbitrary names instead of statically defined list (e.g. `ui_left`, `ui_quick`, etc.). This can mainly be used as part of an input profile to translate inputs into arbitrary dbus events.
> feat(DBus): add support for custom arbitrary dbus events

- src/input/composite_device/mod.rs
Related to @pastaq 's comments on #423, this change will clear the input state (e.g. send button release events, center joystick axes, etc.) on all target devices whenever a source device is disconnected from a composite device.
> fix: Clear the input state (e.g. send release events, center axes, etc.) on target devices on source disconnect

- rootfs/usr/share/inputplumber/capability_maps/ally_type2.yaml
- rootfs/usr/share/inputplumber/devices/50-rog_ally_x.yaml
This change adds limited support for the Ally X controller if Luke Jone's `asus_ally_hid` driver is not present.
> fix(Ally X): add limited functionality if asus_ally_hid driver is not available

- src/input/target/steam_deck.rs
pulled from dmesg
```
[ 2092.962805] usb 9-1: new high-speed USB device number 3 using vhci_hcd
[ 2093.075798] usb 9-1: SetAddress Request (3) to port 0
[ 2093.108661] usb 9-1: New USB device found, idVendor=28de, idProduct=12fd, bcdDevice= 3.00
[ 2093.108671] usb 9-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2093.108677] usb 9-1: Product: ROG Ally X Controller
[ 2093.108682] usb 9-1: Manufacturer: ASUS
[ 2093.121077] input: ASUS ROG Ally X Controller as /devices/platform/vhci_hcd.0/usb9/9-1/9-1:1.0/0003:28DE:12FD.000C/input/input33
[ 2093.129491] input: ASUS ROG Ally X Controller as /devices/platform/vhci_hcd.0/usb9/9-1/9-1:1.1/0003:28DE:12FD.000D/input/input34
[ 2093.121241] hid-generic 0003:28DE:12FD.000C: input,hidraw7: USB HID v1.10 Mouse [ASUS ROG Ally X …
```
> add valve product id for rog ally/x

- src/dbus/interface/composite_device.rs
Currently the target capabilities for dbus would not serialize correctly, creating a list of duplicates:
```bash
$ busctl get-property org.shadowblip.InputPlumber /org/shadowblip/InputPlumber/CompositeDevice0 org.shadowblip.Input.CompositeDevice TargetCapabilities | grep -o '"DBus"'
"DBus"
"DBus"
"DBus"
...
```
This change properly serializes the dbus capability and also uses a hashset to ensure there are no duplicate target capabilities:
```bash
$ busctl get-property org.shadowblip.InputPlumber /org/shadowblip/InputPlumber/CompositeDevice0 org.shadowblip.Input.CompositeDevice TargetCapabilities | grep -oP '"DBus:.*?"'
"DBus:ui_action"
"DBus:ui_context"
"DBus:ui_osk"
...
```
> fix(Composite Device): properly serialize target dbus capabilities and use hashset to remove duplicates

- bindings/dbus-xml/org.shadowblip.Output.ForceFeedback.xml
This change updates the XML docs for the force feedback interface since it was forgotten in the last PR.
> chore(docs): update force feedback binding with enable property

- rootfs/usr/share/inputplumber/capability_maps/msiclaw_type1.yaml
This change updates the capability map for the MSI Claw to use the new combo used by the latest firmware.
> fix(MSI Claw): use updated key combo in newer firmware revisions
